# Generated by Django 5.0.1 on 2024-04-11 14:12

import photos.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=50, validators=[photos.models.User.mail_validation], verbose_name='Email')),
                ('password', models.CharField(db_index=True, max_length=32, verbose_name='Пароль')),
                ('phone', models.CharField(max_length=12, validators=[photos.models.User.number_validation], verbose_name='Номер телефона')),
                ('full_name', models.CharField(max_length=64, verbose_name='Имя Фамилия')),
                ('info', models.CharField(blank=True, max_length=512, null=True, verbose_name='Информация о себе')),
                ('status', models.CharField(choices=[('1', 'Admin'), ('2', 'User')], default=('2', 'User'), max_length=32, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['email'],
            },
        ),
    ]
