# Generated by Django 5.0 on 2024-04-11 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_comment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.CharField(default='Anon', max_length=32),
        ),
        migrations.AlterField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 23, 55, 35, 617395)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 11, 23, 55, 35, 617395)),
        ),
    ]
